function Hd = MakeHighPassFilter(StopBand,PassBand,FSampling);
%MAKEHIGHPASSFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 04-Dec-2014 23:24:33
%

% Chebyshev Type II Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = FSampling;  % Sampling Frequency

Fstop = StopBand;       % Stopband Frequency
Fpass = PassBand;      % Passband Frequency
Astop = 60;          % Stopband Attenuation (dB)
Apass = 0.05;        % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
